/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradeNetworkRouteImport } from './routes/trade-network'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as InquiryRouteImport } from './routes/inquiry'
import { Route as IncotermsRouteImport } from './routes/incoterms'
import { Route as HsCodeRouteImport } from './routes/hs-code'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExportProductsRouteImport } from './routes/export-products'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TradeNetworkRoute = TradeNetworkRouteImport.update({
  id: '/trade-network',
  path: '/trade-network',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiryRoute = InquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const IncotermsRoute = IncotermsRouteImport.update({
  id: '/incoterms',
  path: '/incoterms',
  getParentRoute: () => rootRouteImport,
} as any)
const HsCodeRoute = HsCodeRouteImport.update({
  id: '/hs-code',
  path: '/hs-code',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportProductsRoute = ExportProductsRouteImport.update({
  id: '/export-products',
  path: '/export-products',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/export-products': typeof ExportProductsRoute
  '/faq': typeof FaqRoute
  '/hs-code': typeof HsCodeRoute
  '/incoterms': typeof IncotermsRoute
  '/inquiry': typeof InquiryRoute
  '/knowledge': typeof KnowledgeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trade-network': typeof TradeNetworkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/export-products': typeof ExportProductsRoute
  '/faq': typeof FaqRoute
  '/hs-code': typeof HsCodeRoute
  '/incoterms': typeof IncotermsRoute
  '/inquiry': typeof InquiryRoute
  '/knowledge': typeof KnowledgeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trade-network': typeof TradeNetworkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/export-products': typeof ExportProductsRoute
  '/faq': typeof FaqRoute
  '/hs-code': typeof HsCodeRoute
  '/incoterms': typeof IncotermsRoute
  '/inquiry': typeof InquiryRoute
  '/knowledge': typeof KnowledgeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trade-network': typeof TradeNetworkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/export-products'
    | '/faq'
    | '/hs-code'
    | '/incoterms'
    | '/inquiry'
    | '/knowledge'
    | '/privacy'
    | '/profile'
    | '/quote'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/trade-network'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/export-products'
    | '/faq'
    | '/hs-code'
    | '/incoterms'
    | '/inquiry'
    | '/knowledge'
    | '/privacy'
    | '/profile'
    | '/quote'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/trade-network'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/export-products'
    | '/faq'
    | '/hs-code'
    | '/incoterms'
    | '/inquiry'
    | '/knowledge'
    | '/privacy'
    | '/profile'
    | '/quote'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/trade-network'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  ExportProductsRoute: typeof ExportProductsRoute
  FaqRoute: typeof FaqRoute
  HsCodeRoute: typeof HsCodeRoute
  IncotermsRoute: typeof IncotermsRoute
  InquiryRoute: typeof InquiryRoute
  KnowledgeRoute: typeof KnowledgeRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  QuoteRoute: typeof QuoteRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TradeNetworkRoute: typeof TradeNetworkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trade-network': {
      id: '/trade-network'
      path: '/trade-network'
      fullPath: '/trade-network'
      preLoaderRoute: typeof TradeNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiry': {
      id: '/inquiry'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof InquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incoterms': {
      id: '/incoterms'
      path: '/incoterms'
      fullPath: '/incoterms'
      preLoaderRoute: typeof IncotermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hs-code': {
      id: '/hs-code'
      path: '/hs-code'
      fullPath: '/hs-code'
      preLoaderRoute: typeof HsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-products': {
      id: '/export-products'
      path: '/export-products'
      fullPath: '/export-products'
      preLoaderRoute: typeof ExportProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  ExportProductsRoute: ExportProductsRoute,
  FaqRoute: FaqRoute,
  HsCodeRoute: HsCodeRoute,
  IncotermsRoute: IncotermsRoute,
  InquiryRoute: InquiryRoute,
  KnowledgeRoute: KnowledgeRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  QuoteRoute: QuoteRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TradeNetworkRoute: TradeNetworkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
